/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cities` | `/cities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/groups` | `/groups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/matches` | `/matches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/predictions` | `/predictions`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cities` | `/cities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/groups` | `/groups`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/matches` | `/matches`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/predictions` | `/predictions`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cities${`?${string}` | `#${string}` | ''}` | `/cities${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/groups${`?${string}` | `#${string}` | ''}` | `/groups${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/matches${`?${string}` | `#${string}` | ''}` | `/matches${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/predictions${`?${string}` | `#${string}` | ''}` | `/predictions${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cities` | `/cities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/groups` | `/groups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/matches` | `/matches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/predictions` | `/predictions`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
